- hosts: terraform-ansible
  tasks: 
  - name: create file
    copy: 
      dest: /home/ubuntu/index.html
      content: <h1>up server</h1>
  - name: create server
    shell: "nohup busybox httpd -f -p 8080 &"