- hosts: terraform-ansible
  tasks: 
  - name: install python3 and virtualenv
    apt: 
      pkg: 
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: install django and django rest
    pip: 
      virtualenv: /home/ubuntu/app/venv
      name: 
      - django
      - djangorestframework
